function y = Rotation3(x, theta1, theta2, theta3)
    Rz = [cos(theta1) sin(theta1) 0 0; ...
        -sin(theta1) cos(theta1) 0 0; ...
        0 0 1 0; ...
        0 0 0 1];
    Rx = [1 0 0 0;
        0 cos(theta2) sin(theta2) 0; ...
        0 -sin(theta2) cos(theta2) 0; ...
        0 0 0 1];
    Ry = [cos(theta3) 0 -sin(theta3) 0; ...
        0 1 0 0; ...
        sin(theta3) 0 cos(theta3) 0; ...
        0 0 0 1];
    
    R = Rx * Ry * Rz;
    
    x = [x ones(length(x), 1)];
    
    y = zeros(size(x));
    for i = 1:length(x)
        y(i, :) = R * (x(i, :) - mean(x))' + mean(x)';
    end
    
    y = [y(:, 1), y(:, 2), y(:, 3)]; 
end